# Generated by Django 5.2 on 2025-04-23 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_educationalcontent_challengeparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('lose', 'Losing Weight'), ('gain', 'Gaining Muscle'), ('maintain', 'Maintaining Weight')], max_length=10)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('target_weight', models.FloatField()),
                ('current_weight', models.FloatField()),
                ('activity_per_week', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
