# Generated by Django 5.2 on 2025-04-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'User Goal', 'verbose_name_plural': 'User Goals'},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='activity_per_week',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='current_weight',
        ),
        migrations.AddField(
            model_name='goal',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (little to no exercise)'), ('light', 'Light (exercise 1-3 times/week)'), ('moderate', 'Moderate (exercise 3-5 times/week)'), ('active', 'Active (exercise 6-7 times/week)'), ('very_active', 'Very Active (exercise 2x/day)')], default='moderate', max_length=20),
        ),
    ]
