# Generated by Django 5.2 on 2025-04-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_educationalcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalcontent',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='educationalcontent',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='educationalcontent',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='educationalcontent',
            name='views',
        ),
    ]
