# Generated by Django 5.2 on 2025-04-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_educationalcontent_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
