# Generated by Django 5.2 on 2025-04-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_goal_options_remove_goal_activity_per_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_thumbnails/')),
                ('calories_burned', models.FloatField(blank=True, help_text='Estimated calories burned per minute', null=True)),
                ('muscle_group', models.CharField(choices=[('fullbody', 'Full Body Exercise'), ('chest', 'Chest Exercise'), ('back', 'Back Exercise'), ('legs', 'Leg Exercise'), ('shoulders', 'Deltoids Exercise'), ('arms', 'Arm Exercise'), ('core', 'Core Exercise')], default='fullbody', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], default='intermediate', max_length=20)),
                ('equipment', models.CharField(choices=[('none', 'No Equppment Needed'), ('dumbells', 'Dumbells'), ('pull_up', 'Pull Up Bar'), ('others', 'Others')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
