# Generated by Django 5.2 on 2025-04-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_educationalcontent_rating_educationalcontent_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='category',
            field=models.CharField(choices=[('workouts', 'Workouts'), ('nutrition', 'Nutrition')], default='workouts', max_length=20),
        ),
    ]
