# Generated by Django 5.2 on 2025-04-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_thumbnails/')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('carbs', models.FloatField(blank=True, help_text='Grams of carbs per 100g ', null=True)),
                ('protein', models.FloatField(help_text='Grams of carbs per 100g')),
                ('fat', models.FloatField(help_text='Grams of carbs per 100g')),
                ('food_type', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('grain', 'Grain / Cereal'), ('protein', 'Protein (Meat, Fish, Eggs)'), ('dairy', 'Dairy'), ('fat', 'Fats & Oils'), ('snack', 'Snacks'), ('beverage', 'Beverages'), ('other', 'Other')], default='other', help_text='Category of the food', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
