# Generated by Django 5.2 on 2025-04-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_educationalcontent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalcontent',
            name='duration',
        ),
    ]
