# Generated by Django 5.2 on 2025-04-26 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_subscriptionplan_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='instructor',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='nutritionist',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_instructor': True, 'specialization': 'nutritionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutritionist_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_instructor': True, 'specialization': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
