# Generated by Django 5.2 on 2025-04-27 03:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_subscriptionplan_instructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('plan_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance Training'), ('maintain', 'Mantain Weight')], default='general', max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(help_text='Duration in weeks', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('sets', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('reps', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes (for cardio exercises)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of exercise in the workout')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
                ('fitness_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.fitnessplan')),
            ],
            options={
                'ordering': ['day', 'order'],
                'unique_together': {('fitness_plan', 'exercise', 'day')},
            },
        ),
    ]
