# Generated by Django 5.2 on 2025-04-27 03:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fitnessplan_fitnessplanexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('plan_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Weight Maintenance'), ('diabetic', 'Diabetic Diet'), ('keto', 'Keto Diet'), ('vegetarian', 'Vegetarian')], default='maintenance', max_length=20)),
                ('daily_calorie_target', models.PositiveIntegerField(help_text='Target calories per day')),
                ('duration_weeks', models.PositiveIntegerField(help_text='Duration in weeks', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('afternoon_snack', 'Afternoon Snack'), ('dinner', 'Dinner'), ('evening_snack', 'Evening Snack')], max_length=20)),
                ('quantity_grams', models.PositiveIntegerField(help_text='Quantity in grams', validators=[django.core.validators.MinValueValidator(1)])),
                ('day', models.PositiveIntegerField(help_text='Day number in the plan (1-7 for weekly plans)', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of food in the meal')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_foods', to='api.mealplan')),
            ],
            options={
                'ordering': ['day', 'meal_time', 'order'],
                'unique_together': {('meal_plan', 'food', 'day', 'meal_time')},
            },
        ),
    ]
