# Generated by Django 5.2 on 2025-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_mealplan_mealfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessplan',
            name='difficulty',
            field=models.CharField(choices=[('sedentary', 'Very Easy (Sedentary: little to no exercise)'), ('light', 'Easy (Light: 1-3 times/week)'), ('moderate', 'Normal (Moderate: 3-5 times/week)'), ('active', 'Hard (Active: 6-7 times/week)'), ('very_active', 'Very Hard (Very Active: 2x/day)')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='fitness_plans/'),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='plan_type',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance Training'), ('maintain', 'Maintain Weight')], default='weight_loss', max_length=20),
        ),
    ]
