# Generated by Django 5.2 on 2025-04-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_fitnessplan_difficulty_fitnessplan_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='image',
            field=models.ImageField(blank=True, help_text='Image representing the meal plan', null=True, upload_to='meal_plans/'),
        ),
    ]
