# Generated by Django 5.2 on 2025-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeparticipant',
            name='progress',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
