# Generated by Django 5.2 on 2025-05-08 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_challengeparticipant_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('fitness_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.fitnessplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plan_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fitness Plan User',
                'verbose_name_plural': 'Fitness Plan Users',
                'unique_together': {('user', 'fitness_plan')},
            },
        ),
    ]
