# Generated by Django 5.2 on 2025-05-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_mealplanuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessplanuser',
            name='progress',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
