# Generated by Django 5.2 on 2025-05-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='read',
            new_name='is_read',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan',
            field=models.CharField(choices=[('premium', 'Premium')], max_length=10),
        ),
    ]
